//
//  MessagesViewController.swift
//  SportLGBT
//
//  Created by Mihail on 01.11.2024.
//

import UIKit
import Messages

class MessagesViewController: MSMessagesAppViewController {
    var sportGaysVC: SportGayVC!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        print("viewDidLoad")
        sportGaysVC = SportGayVC(stickerSize: .regular)
        sportGaysVC.view.frame = self.view.frame

        self.addChild(sportGaysVC)
        sportGaysVC.didMove(toParent: self)
        self.view.addSubview(sportGaysVC.view)

    }
    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        print("willBecomeActive")
        
        sportGaysVC.loadStickers()
        sportGaysVC.stickerBrowserView.reloadData()
    }
    
    override func didResignActive(with conversation: MSConversation) {
        print("didResignActive")
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
        
        // Use this method to trigger UI updates in response to the message.
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
    
        // Use this method to prepare for the change in presentation style.
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
    }

}
